/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.12).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.HostName;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-01-27T07:41:01.605Z")

public interface TestServerApi {

    @ApiOperation(value = "Find Server Host Name", nickname = "findContainerHostname", notes = "Display Host Names of Containers on a Cluster Distribution", response = HostName.class, tags={ "pet", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "successful operation", response = HostName.class) })
    @RequestMapping(value = "/testServer",
        produces = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<HostName> findContainerHostname() {
        return new ResponseEntity("", HttpStatus.OK);
    }

}
