apiVersion: image.openshift.io/v1    
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "hostname-api-service"
spec:
  runPolicy: "Serial"
  source:
    type: Git
    git:
      ref: master
      uri: 'https://github.com/Piroddi/SimpleSpringServer'
  strategy:
    type: Docker
    dockerStrategy:
        noCache: true 
  output:
  to:
    kind: "ImageStreamTag"
    name: hostname-api-service:latest 
  triggers:
  - type: ConfigChange
  - type: ImageChange